### ISSUE TITLE
Crash when using taskboard and going through other tasks in jupiter

### ISSUE THREAD

**Issue by ForkinIsaac** [lTheon/iTheon-New-Tasks-Addon#34]
Fatal Error

Expression :

<no expression>

Function

: CScriptEngine::lua_pcall_failed

File

: D:\a\xray-monolith\xray-monolith\src\xrServerEntities\script_engine.cpp

Line

: 262

Description : fatal error

Arguments

1: [Lua] d:/stalker anomaly\gamedata\scripts\tasks_nta_stash.script(73):

LUA error: d:/stalker anomaly\gamedata\scripts\tasks_nta_stash.script:73: attempt to get length of local 'stashes_on_level' (a nil value)

Check log for details

stack trace:

Press OK to abort execution

OK

**Comment by lTheon** [comment]
This issue has been fixed in the latest version. Try updating the mod.

**Comment by ForkinIsaac** [comment]
> This issue has been fixed in the latest version. Try updating the mod.

It's still happening to me. I have downloaded the latest version and enabled it in mo2

**Comment by lTheon** [comment]
Are you using some modpack or built your own list?
If vanilla logic of fetching stash data is modified in your list, then it might impact this mod

**Comment by ForkinIsaac** [comment]
> Are you using some modpack or built your own list? If vanilla logic of fetching stash data is modified in your list, then it might impact this mod
Building my own list yeah
Could it be caused by ZLM-ZCP Loot Module revised mod?

**Comment by lTheon** [comment]
ZLM-ZCP affects stashes logic, so yeah - it can impact it. I've got a dirty workaround for you to try out though. Open `z_nta_stashes_utils.script` and remove the `on_game_load` function. Replace it with the snippet below.
```
function on_game_load()
    nta_utils.set_timeout(function ()
        populate_stashes_by_levels_table()
    end, 1)
end
```

This will slow down the execution of the function that collects stash data by 1 second (i.e. you should not play around with taskboard after loading the game for that long. If this doesn't help, try changing the `1` that comes after the `end, ` to `3`. That should be enough to wait for whatever other scripts are doing with this stuff. If it still doesn't work, then I'm afraid I can't help you with this one. Debugging custom lists is too time consuming

**Comment by ForkinIsaac** [comment]
> ZLM-ZCP affects stashes logic, so yeah - it can impact it. I've got a dirty workaround for you to try out though. Open `z_nta_stashes_utils.script` and remove the `on_game_load` function. Replace it with the snippet below.
> 
> ```
> function on_game_load()
>     nta_utils.set_timeout(function ()
>         populate_stashes_by_levels_table()
>     end, 1)
> end
> ```
> 
> This will slow down the execution of the function that collects stash data by 1 second (i.e. you should not play around with taskboard after loading the game for that long. If this doesn't help, try changing the `1` that comes after the `end, ` to `3`. That should be enough to wait for whatever other scripts are doing with this stuff. If it still doesn't work, then I'm afraid I can't help you with this one. Debugging custom lists is too time consuming

Yeah that's work. Can you please also explain why should I play around with taskboard?

**Comment by ForkinIsaac** [comment]
> I've only meant for you to not use the taskboard for 1 second after you load the game so that this script kicks in. That shouldn't be too problematic, right? ^_^

Ohh it's not a problem I thought it would cause issues with the taskboard or the tasks. Thanks for helping me out.
